(define (average x y)
    (/ (+ x y)
       2.0))

(define (make-point x y)
    (cons x y))
(define (x-point p)
    (car p))
(define (y-point p)
    (cdr p))
(define (print-point p)
    (newline)
    (display "(")
    (display (x-point p))
    (display ",")
    (display (y-point p))
    (display ")"))

(define (make-segment sp ep)
    (cons sp ep))
(define (start-segment sg)
    (car sg))
(define (end-segment sg)
    (cdr sg))
(define (midpoint-segment sg)
    (cons (average (+ (x-point (start-segment sg))
                (x-point (end-segment sg)))
             )
          (average (+ (y-point (start-segment sg))
                (y-point (end-segment sg)))
             )))

(define (make-rectangle p q)
    (cons p q))
(define (perimeter rect)
    (* 2 (+ (- (x-point (end-segment rect))
               (x-point (start-segment rect)))
            (- (y-point (end-segment rect))
               (y-point (start-segment rect))))))
(define (area rect)
    (* (- (x-point (end-segment rect))
          (x-point (start-segment rect)))
       (- (y-point (end-segment rect))
          (y-point (start-segment rect)))))

(define rect (make-rectangle (make-point 1 2) (make-point 5 8)))
(perimeter rect)
(area rect)
