(define (average x y)
    (/ (+ x y)
       2.0))

(define (make-point x y)
    (cons x y))
(define (x-point p)
    (car p))
(define (y-point p)
    (cdr p))
(define (print-point p)
    (newline)
    (display "(")
    (display (x-point p))
    (display ",")
    (display (y-point p))
    (display ")"))

(define (make-segment sp ep)
    (cons sp ep))
(define (start-segment sg)
    (car sg))
(define (end-segment sg)
    (cdr sg))
(define (midpoint-segment sg)
    (cons (average (+ (x-point (start-segment sg))
                (x-point (end-segment sg)))
             )
          (average (+ (y-point (start-segment sg))
                (y-point (end-segment sg)))
             )))

(define sp (make-point 1 2))
(print-point sp)
(define ep (make-point 5 6))
(print-point ep)
(define sg (make-segment sp ep))
(print-point (start-segment sg))
(print-point (end-segment sg))
(print-point (midpoint-segment sg))
